apiVersion: apps/v1
kind: Deployment
metadata:
  name: joo-service
  namespace: eris-be
  labels:
    app: joo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joo-service
  template:
    metadata:
      labels:
        app: joo-service
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: joo-service
          image: harbor.oke.com:30217/joo-test/joo-service:latest
          ports:
            - containerPort: 8080

