apiVersion: v1
kind: Service
metadata:
  name: joo-service
  namespace: eris-be
spec:
  selector:
    app: joo-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
